services:
  gitlab:
    image: docker.io/gitlab/gitlab-ce:17.11.0-ce.0
    container_name: gitlab
    shm_size: '256m'
    environment: {}
    networks:
      - proxy
    volumes:
      - /local/apps/gitlab/config:/etc/gitlab
      - /local/apps/gitlab/logs:/var/log/gitlab
      - /local/apps/gitlab/data:/var/opt/gitlab
    ports:
      - '2424:22'
    labels:
      - traefik.enable=true
      - traefik.http.services.gitlab.loadbalancer.server.port=80
      - traefik.http.services.gitlab.loadbalancer.server.scheme=http
      - traefik.http.routers.gitlab.service=gitlab
      - traefik.http.routers.gitlab.rule=Host(`gitlab.local.domain.com`)
      - traefik.http.routers.gitlab.entrypoints=https
      - traefik.http.routers.gitlab.tls=true
    restart: unless-stopped
networks:
  proxy:
    external: true