---
- name: System Maintenance - Update and Docker Cleanup Playbook
  hosts: all  
  become: yes  
  
  tasks:
    # System Update Task
    - name: Run system update
      ansible.builtin.include_tasks: ../common/system-update.yml
    
    # Docker Cleanup Task
    - name: Check if Docker command exists
      shell: "command -v docker"
      register: docker_check
      changed_when: false
      failed_when: false
      become: yes

    - name: Prune unused Docker images and containers
      shell: docker system prune -f --volumes
      register: prune_result
      when: docker_check.rc == 0

    - name: Display Docker prune results
      debug:
        msg: "Docker prune completed on {{ inventory_hostname }}. Output: {{ prune_result.stdout }}"
      when: docker_check.rc == 0

    - name: Inform if Docker was not found
      debug:
        msg: "Docker not found on {{ inventory_hostname }}. Skipping prune."
      when: docker_check.rc != 0