# This playbook installs Docker and Docker Compose on a Linux host using official repositories.
    - name: Include system update tasks
      ansible.builtin.include_tasks: system-update.yml

    - name: Install prerequisites (APT)
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
      when: ansible_pkg_mgr == 'apt'

    - name: Install prerequisites (DNF)
      dnf:
        name:
          - curl
          - ca-certificates
          - gnupg
        state: present
      when: ansible_pkg_mgr == 'dnf'

    - name: Add Docker GPG key (APT)
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present
      when: ansible_pkg_mgr == 'apt'

    - name: Add Docker repository (APT)
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        state: present
      when: ansible_pkg_mgr == 'apt'

    - name: Add Docker repository (DNF)
      get_url:
        url: https://download.docker.com/linux/rhel/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        mode: '0644'
      when: ansible_pkg_mgr == 'dnf'

    - name: Install Docker packages (APT)
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
      when: ansible_pkg_mgr == 'apt'

    - name: Install Docker packages (DNF)
      dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
      when: ansible_pkg_mgr == 'dnf'

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add user to docker group
      user:
        name: "{{ ansible_user | default(ansible_ssh_user) | default('root') }}"
        groups: docker
        append: yes

    - name: Verify Docker installation
      shell: docker --version
      register: docker_version
      changed_when: false

    - name: Verify Docker Compose installation
      shell: docker compose version
      register: compose_version
      changed_when: false

    - name: Display versions
      debug:
        msg: 
          - "Docker: {{ docker_version.stdout }}"
          - "Docker Compose: {{ compose_version.stdout }}"