---
- name: Install Docker on Debian
  hosts: all
  become: yes 

  tasks:
    - name: check if Docker is already installed
      stat:
        path: /usr/bin/docker
      register: docker_installed
    - name: fail if Docker already installed
      fail:
        msg: "Docker is already installed on this host."
      when: docker_installed.stat.exists
      
    - name: Install Docker using convenience script
      shell: curl -sSL https://get.docker.com/ | CHANNEL=stable sh
      args:
        creates: /usr/bin/docker

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Verify Docker installation
      shell: docker --version
      register: docker_version
      changed_when: false

    - name: Display Docker version
      debug:
        msg: "Docker installed: {{ docker_version.stdout }}"
    
    - name: check docker service status
      systemd:
        name: docker
      register: docker_status

    - name: Display Docker service status
      debug:
        msg: "Docker service status: {{ docker_status.status.ActiveState }}"