# This playbook updates the apt cache and performs a system upgrade on Debian-based systems.
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      ignore_errors: yes

    - name: Perform system upgrade
      apt:
        upgrade: dist
      ignore_errors: yes