services:
  gotify:
    image: gotify/server:latest
    container_name: gotify
    volumes:
      - /nfs/apps/gotify:/app/data  
    labels:
      - traefik.enable=true
      - traefik.http.routers.gotify.rule=Host(`gotify.local.domain.com`)
      - traefik.http.routers.gotify.entrypoints=https
      - traefik.http.routers.gotify.tls=true
      - traefik.http.services.gotify.loadbalancer.server.port=80
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true  
