---
- name: Install and configure Oh My Zsh
  hosts: all
  become: true
  tasks:
    - name: Install required packages
      package:
        name:
          - zsh
          - git
          - curl
          - fd-find
        state: present

    - name: Install Oh My Zsh
      shell: |
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
      args:
        creates: "{{ ansible_env.HOME }}/.oh-my-zsh"
      become: false

    - name: Install zsh-autosuggestions plugin
      shell: |
        git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
      args:
        creates: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
      become: false

    - name: Install zsh-syntax-highlighting plugin
      shell: |
        git clone https://github.com/zsh-users/zsh-syntax-highlighting ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
      args:
        creates: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
      become: false

    - name: Install FZF
      shell: |
        git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
        ~/.fzf/install --all
      args:
        creates: "{{ ansible_env.HOME }}/.fzf"
      become: false

    - name: Set zsh as default shell
      user:
        name: "{{ ansible_env.USER }}"
        shell: /bin/zsh

    - name: Download zshrc configuration
      get_url:
        url: "https://raw.githubusercontent.com/m7mdbinghaith/homelab/testing/ansible/files/zshrc"
        dest: "{{ ansible_env.HOME }}/.zshrc"
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
        mode: '0644'
      become: false
