services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io:latest
    container_name: changedetection
    hostname: changedetection
    user: 1000:1000
    volumes:
      - /nfs/apps/changedetection/datastore:/datastore
    networks:
      - proxy
      - internal
    depends_on:
      playwright-chrome:
        condition: service_started
    environment:
      - PLAYWRIGHT_DRIVER_URL=ws://playwright-chrome:3000
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.changedetection.rule=Host(`changedetection.local.domain.com`)
      - traefik.http.routers.changedetection.entrypoints=https
      - traefik.http.routers.changedetection.tls=true
      - traefik.http.services.changedetection.loadbalancer.server.port=5000
      - traefik.docker.network=proxy
  playwright-chrome:
    hostname: playwright-chrome
    image: browserless/chrome
    networks:
      - internal
    restart: unless-stopped
    environment:
      - SCREEN_WIDTH=1280
      - SCREEN_HEIGHT=800
      - SCREEN_DEPTH=16
      - ENABLE_DEBUGGER=false
      - PREBOOT_CHROME=true
      - CONNECTION_TIMEOUT=300000
      - MAX_CONCURRENT_SESSIONS=10
      - CHROME_REFRESH_TIME=600000
      - DEFAULT_BLOCK_ADS=true
      - DEFAULT_STEALTH=true
      - DEFAULT_IGNORE_HTTPS_ERRORS=true
    shm_size: '2gb'
networks:
  internal:
    name: changedetection-internal
  proxy:
    external: true