---
- name: System Update and Upgrade Playbook
  hosts: all  
  become: yes  
  
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600  
      
    - name: Perform full system upgrade
      apt:
        upgrade: dist
        
    - name: Check if reboot is required
      register: reboot_required
      stat:
        path: /var/run/reboot-required
        
    - name: Notify if reboot is needed
      debug:
        msg: "Reboot is required to complete system updates"
      when: reboot_required.stat.exists